// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _4Ucode_sms.Data.Context;

#nullable disable

namespace _4Ucode_sms.Domain.Migrations
{
    [DbContext(typeof(MeuDbContext))]
    [Migration("20230120150724_Initial_6")]
    partial class Initial_6
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Business.Models.ContatoDocumento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("numero")
                        .IsRequired()
                        .HasColumnType("varchar(11)");

                    b.HasKey("Id");

                    b.ToTable("tb_Contatos", (string)null);
                });

            modelBuilder.Entity("Business.Models.EnvioDocumento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Enviado")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("NumeroId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TextoEnvio")
                        .IsRequired()
                        .HasColumnType("varchar(260)");

                    b.HasKey("Id");

                    b.HasIndex("NumeroId");

                    b.ToTable("tb_Envio", (string)null);
                });

            modelBuilder.Entity("Business.Models.EnvioDocumento", b =>
                {
                    b.HasOne("Business.Models.ContatoDocumento", "Numero")
                        .WithMany("EnvioDocumentos")
                        .HasForeignKey("NumeroId")
                        .IsRequired();

                    b.Navigation("Numero");
                });

            modelBuilder.Entity("Business.Models.ContatoDocumento", b =>
                {
                    b.Navigation("EnvioDocumentos");
                });
#pragma warning restore 612, 618
        }
    }
}
